
paper: ruthefjord-fdg-2015.bib ruthefjord-fdg-2015.tex
	pdflatex ruthefjord-fdg-2015.tex
	bibtex ruthefjord-fdg-2015
	pdflatex ruthefjord-fdg-2015.tex
	pdflatex ruthefjord-fdg-2015.tex

clean:
	rm -f ruthefjord-fdg-2015.pdf *.log *.aux *.bbl *.blg *.out
